config/routes.rb
Rails.application.routes.draw do

  root "houses#index"

  resources :houses do
  	resources :orders, only: [:new, :create]
  end

  resources :users do
    #this resource depends on a user
  	resources :houses, only: [:show, :index]
  	resources :orders, only: [:show]
    
  end

  resource :session, only: [:new, :create, :destroy]
  resources :orders

end

app/models/house.rb
class House < ActiveRecord::Base
	has_attached_file :image, default_url: "missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_many :orders
	belongs_to :user

	geocoded_by :address
	before_validation :geocode

	validate :latitude, presence: true
	validate :longitude, presence: true

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :house
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, confirmation: true, length: { minimum: 8 }

	has_secure_password

	# Gives us @user.orders e.g @user.orders.new, @user.order.all
	has_many  :orders
	has_many  :houses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	helper_method :require_user
	helper_method :current_user
	helper_method :current_user?
	def current_user
		if session[:user_id].present?
			User.find(session[:user_id])
		end
	end

	def current_user?
		current_user.present?
	end

	def require_user
		if current_user?
			current_user
		else
			flash[:error] = "You must be logged in to do that"
			redirect_to new_session_path
		end
	end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
  	@houses = House.all
  end

  def show
  	@house = House.find(params[:id])
  end

  def new
    require_user
    @user = current_user
  	@house = @user.houses.new
  end

  def create
    require_user
    @user = current_user
  	@house = @user.houses.new(house_params)
  	@house.save
  	redirect_to house_path(@house)
  end

  def edit
    require_user
    @user = current_user
    @house = @user.houses.find(params[:id])
  end

  def update
    require_user
    @user = current_user
    @house = @user.houses.find(params[:id])
    if @house.update(house_params)
      flash[:success] = "Your house was updated"
      redirect_to house_path(@house)
    else
      flash[:error] = "Oops somethinig went wrong"
      render :edit
    end
  end

  def destroy
  end

  private
  def house_params
  	params.require(:house).permit(:title, :address, 
  		:description, :price_in_pence, 
  		:number_of_rooms, :max_guests, :image)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  	@user = current_user
  	@orders = @user.orders.all 
  end

  def show
  	require_user
  	@user = current_user
  	@order = @user.orders.find
  end

  def new
  	require_user
  	@house = House.find(params[:house_id])
    @order = @house.orders.new
  end

  def create
  	require_user

    @house = House.find(params[:house_id])

    @order = @house.orders.new(order_params)

    @order.user = current_user

    if @order.save
  		flash[:success] = "Thanks for placing your order"
  		redirect_to orders_path

      # Set your secret key: remember to change this to your live secret key in production
      # See your keys here https://dashboard.stripe.com/account
      Stripe.api_key = Rails.application.secrets.stripe_secret

      # Get the credit card details submitted by the form
      token = @order.stripe_token

      # Create the charge on Stripe's servers - this will charge the user's card
      begin
        charge = Stripe::Charge.create(
          :amount => @order.house.price_in_pence,
          :currency => "gbp",
          :card => token,
          :description => "payinguser@example.com"
        )
      rescue Stripe::CardError => e
        # The card has been declined
      flash[:error] = e
      end


  	else
  		flash[:error] = "Something went wrong"
  		render :new
  	end
  end

  private
  def order_params
  	params.require(:order).permit(:stripe_token)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@username = params[:session][:username]
  	@password = params[:session][:password]

	@user = User.find_by(username: @username)
  	if @user.present? and @user.authenticate(@password)
	  	session[:user_id] = @user.id
	  	redirect_to root_path
	else
		flash[:error] = "Oops! Try again..."
		render :new
	end
  end

  def destroy
  	reset_session
  	flash[:success] = "You've susccessfully logged out"
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      flash[:success] = "thanks for signing up"
  	 redirect_to root_path
    else
      flash[:error] = "Ooops, try again"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = "Your user was updated"
      redirect_to user_path(@user)
    else
      flash[:error] = "Oops somethinig went wrong"
      render :edit
    end
  end

  private
  def user_params
  	params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/houses/edit.html.erb
<%= simple_form_for [@user, @house], url: house_path, method: :put do |f| %>

	<%= f.input :title %>
	<%= f.input :address %>
	<%= f.input :image %>
	<%= f.input :description %>
	<%= f.input :price_in_pence %>
	<%= f.input :number_of_rooms %>
	<%= f.input :max_guests %>
	
	<% if params[:action] == "edit" %>
		<%= f.button :submit, "Save" %>
	<% else %>
		<%= f.button :submit, "Add a room" %>
	<% end %>


<% end %>

app/views/houses/index.html.erb
<section class="rooms">

		<% @houses.each do |house| %>

			<div class="room">

				<%= image_tag house.image.url %>
				<div>
					<h2>
						<%= link_to house.title, house_path(house.id) %>
					</h2>

					<p><%=  house.address %></p>

					<p>£<%=  house.price_in_pence / 100 %>/wk</p>
				</div>

			</div>

		<% end %>

</section>

app/views/houses/new.html.erb
<%= simple_form_for [@user, @house], url: houses_path, method: :post do |f| %>

	<%= f.input :title %>
	<%= f.input :address %>
	<%= f.input :image %>
	<%= f.input :description %>
	<%= f.input :price_in_pence %>
	<%= f.input :number_of_rooms %>
	<%= f.input :max_guests %>
	
	<% if params[:action] == "edit" %>
		<%= f.button :submit, "Save" %>
	<% else %>
		<%= f.button :submit, "Add a room" %>
	<% end %>


<% end %>

app/views/houses/show.html.erb
<section class= "room">

	<h2>
		<%= @house.title %>
	</h2>

	<div class="address">

		<%= @house.address %>

	</div>

	<div class="image">
		
				<%= image_tag @house.image.url %>
	</div>

	<div class="map" data-lat='<%= @house.latitude %>' data-lng='<%= @house.longitude%>' >

	</div>

	<div class="description">
		<%= @house.description %>
	</div>

	<div class="user">
		<p>Added by <%= @house.user.username %></p>
	</div>

	<div class="actions">
		<%= link_to "Book room", new_house_order_path(@house.id), class: 'button' %>
		<%= link_to "Edit", edit_house_path(@house.id), class: 'button' %>
		<%= link_to "Delete", house_path(@house.id), method: :delete, class: 'button' %>
	</div>
</section>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Onboard</title>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_fy9Zps4yuxSNHtPrVr5vr02d');
  // ...
</script>
</head>
<body>

<div class="container">
  <header class="row">
    <h1 class="two columns">


      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </h1>

    <form action="" class="three columns">
      <input type="text">
    </form>

    <nav class="seven columns">
      <% if current_user? %>
        <%= current_user.username %>
        <%= link_to "Dashboard", "#" %>
        <%= link_to "Add a room", new_house_path %>
        <%= link_to "Orders", orders_path %>
        <%= link_to "Log out", session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Log in", new_session_path %>
      <% end %>
    </nav>
  </header>

  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>

  <article class="row">
    <%= yield %>
  </article>

  <footer>
    <p>&copy; <%= Date.today.year %> Onboard Ltd</p>
  </footer>
</div>

</body>
</html>

app/views/orders/index.html.erb
<section class= "room">

	<%= @orders.each do |order| %>
		<div class="room">

			<h2><%= order.house.title %></h2>
		
			<p><%= order.house.address %></p>

			<p><%= order.house.price_in_pence %></p>

			<p><%= image_tag order.house.image.url %></p>
			
		</div>
	
	<% end %>

</section>

app/views/orders/new.html.erb
<%= simple_form_for [@user, @order], url: house_orders_path(@house.id), method: :post do |f| %>
	
	<span class="payment-errors"></span>

	  <div class="form-row">
	    <label>
	      <span>Card Number</span>
	      <input type="text" size="20" data-stripe="number"/>
	    </label>
	  </div>

	  <div class="form-row">
	    <label>
	      <span>CVC</span>
	      <input type="text" size="4" data-stripe="cvc"/>
	    </label>
	  </div>

	  <div class="form-row">
	    <label>
	      <span>Expiration (MM/YYYY)</span>
	      <input type="text" size="2" data-stripe="exp-month"/>
	    </label>
	    <span> / </span>
	    <input type="text" size="4" data-stripe="exp-year"/>
	  </div>

	  <button type="submit">Submit Payment</button>

	  <script type="text/javascript">
		jQuery(function($) {
		  $('#new_order').submit(function(event) {
		    var $form = $(this);

		    // Disable the submit button to prevent repeated clicks
		    $form.find('button').prop('disabled', true);

		    Stripe.card.createToken($form, stripeResponseHandler);

		    // Prevent the form from submitting with the default action
		    return false;
  			});
		});

		function stripeResponseHandler(status, response) {
		  var $form = $('#new_order');

		  if (response.error) {
		    // Show the errors on the form
		    $form.find('.payment-errors').text(response.error.message);
		    $form.find('button').prop('disabled', false);
		  } else {
		    // response contains id and card, which contains additional card details
		    var token = response.id;
		    // Insert the token into the form so it gets submitted to the server
		    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
		    // and submit
		    $form.get(0).submit();
		  }
		};


	  </script>

<% end %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>

	<%= f.input :username %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>

	
	<%= f.button :submit, "Create account" %>

<% end %>